server:
  port: 7001

spring:
  application:
    name: gt-system
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
  config:
    import:
      - optional:nacos:gt.yaml
      - optional:nacos:gt-@profile.name@.yaml

# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS